### PR TITLE
Upgrade dependencies to their latest versions

### PR DESCRIPTION
**Pull request by ohsayan**

### CODE REVIEW

**Comment by imbolc** [comment]
Thank you :) I have a question though, would there be implications if we drop patch numbers (make it 0.16 instead of 0.16.0)?

**Comment by ohsayan** [comment]
Sure thing. I'll do that (the initial title's verbosity owes its credits to the GH extension I use :D)

**Comment by ohsayan** [comment]
The only issue is that patches (according to semver), occasionally have the choice to break[^1]

[^1]: https://semver.org/#what-if-i-inadvertently-alter-the-public-api-in-a-way-that-is-not-compliant-with-the-version-number-change-ie-the-code-incorrectly-introduces-a-major-breaking-change-in-a-patch-release

**Comment by imbolc** [comment]
Right, but I'd expect a user to pin a particular patch on their application level. E.g. if I add `cookie = 0.16.1` into my application deps, I'd expect Cargo use to use this version for `tower-cookies` too. It's published, thank you :pray:

**Comment by ohsayan** [comment]
Agreed. Thanks for the quick release; will bump the dep now :)

**Pull request merged**
