### PR TITLE
14 question how to remove cookies

### LINKED ISSUE #14: [Question] How to remove cookies?
I am having some problem figuring out how to remove cookies.

Cause you need to have the cookie in order to remove it, which to me is weird as i would expect to remove it by it's name.
But if you get the cookie beforehand you can't use that cookie to remove it cause of lifetime issues.
Are you supposed to just create a dummy cookie like in the Counter example?

```
    async fn handler(Extension(cookies): Extension<Cookies>) {
        let key = KEY.get().unwrap();
        let private_cookies = cookies.signed(key);
        cookies.remove(Cookie::new(COOKIE_NAME, ""));
    }
```

### PR DESCRIPTION
**Pull request by imbolc**
Closes #14

### CODE REVIEW

**Comment by davidpdrsn** [comment]
Maybe I'm misunderstanding something about how `tower-cookies` or `cookie` works but does `jar.remove(Cookie::named("foo"))` not work?

**Comment by imbolc** [comment]
`Cookie::named("foo")` is just an alias for `Cookie::new("foo", "")`. But [CookieJar::remove](https://docs.rs/cookie/latest/cookie/struct.CookieJar.html#method.remove) says:

> To properly generate the removal cookie, cookie must contain the same path and domain as the cookie that was initially set.

So `Cookie::named` method seems to work only for cookies with `path == "/"`. As the root path is the default, no one seem to change it yet and report the bug.

Also this PR makes it possible to do just `cookies.remove("foo")` instead of `cookies.remove(Cookie::named("foo"))`, which is arguable more intuitive

**Comment by davidpdrsn** [comment]
Hm I'm not quite sure which is more appropriate `cookies.remove("foo")` or `cookies.remove(Cookie::named("foo"))`. Its up to you 😊

For axum-extra I think we'll with `cookies.remove(Cookie::named("foo"))` since thats what `cookie` does.

**Comment by imbolc** [comment]
The only distinction is that `cookies.remove("foo")` would remove `Cookie::build("foo", "bar").path("/baz")` while `cookies.remove(Cookie::named("foo"))` won't :)

**Pull request closed without merging**
